#!/bin/sh

 

#Get number of fields from data file

cols=`awk -F "," '{ print NF }' $1 | sort -n | tail -1`

 

i=1

 

while (( $i <= $cols ))

do
  tpcell=''

  #Get values of the cells and build the transposed row
  for x in `cut -d"," -f$i $1 | sed 's/^$/NA/'`
  do

    #Assign transposed cell values

    tpcell=$tpcell$x","

  done

 

  #Output each transposed line of the matrix

  tpline=`echo "${tpcell%?}"`

  echo "$tpline"

 

  #Increment the count

  i=`expr $i + 1`

done
